"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILFieldsetElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILFieldsetElement guid: (GUID fromString: '{8a41b448-e2d1-4822-a6ac-c3e231a8cc45}')!
ILFieldsetElement comment: ''!
!ILFieldsetElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILFieldsetElement methodsFor!

tag	^'fieldset'! !
!ILFieldsetElement categoriesFor: #tag!accessing!public! !

