"Filed out from Dolphin Smalltalk 7"!

ILElementTest subclass: #ILHorizontalRuleElementTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILHorizontalRuleElementTest guid: (GUID fromString: '{635b2296-eba1-4627-aa3a-34f12f0f104a}')!
ILHorizontalRuleElementTest comment: ''!
!ILHorizontalRuleElementTest categoriesForClass!Iliad-Tests-Elements! !
!ILHorizontalRuleElementTest methodsFor!

setUp	e := ILHorizontalRuleElement new!

testTag	self assert: e tag equals: 'hr'! !
!ILHorizontalRuleElementTest categoriesFor: #setUp!public!running! !
!ILHorizontalRuleElementTest categoriesFor: #testTag!public!testing! !

