"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #ILJsonSyntaxError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILJsonSyntaxError guid: (GUID fromString: '{d8ec75df-f4e8-4342-bef0-0fef39032d0e}')!
ILJsonSyntaxError comment: 'Class Json signals instances of me when an input stream contains invalid JSON input.'!
!ILJsonSyntaxError categoriesForClass!Iliad-Core-lib-JSON! !
