"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILPreElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILPreElement guid: (GUID fromString: '{d6df3bf4-dd7b-435f-8239-f87e2430cb08}')!
ILPreElement comment: ''!
!ILPreElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILPreElement methodsFor!

tag	^'pre'! !
!ILPreElement categoriesFor: #tag!accessing!public! !

