"Filed out from Dolphin Smalltalk 7"!

ILElementTest subclass: #ILRSSCommentsElementTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILRSSCommentsElementTest guid: (GUID fromString: '{06b66f39-b20c-4e8a-aecc-6ae608925655}')!
ILRSSCommentsElementTest comment: ''!
!ILRSSCommentsElementTest categoriesForClass!Iliad-Tests-RSS! !
!ILRSSCommentsElementTest methodsFor!

setUp	e := ILRSSCommentsElement new!

testTag	self assert: e tag equals: 'comments'! !
!ILRSSCommentsElementTest categoriesFor: #setUp!public!running! !
!ILRSSCommentsElementTest categoriesFor: #testTag!public!testing! !

