"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILSpanElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILSpanElement guid: (GUID fromString: '{d123a496-8811-4f14-8813-2c895803816e}')!
ILSpanElement comment: ''!
!ILSpanElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILSpanElement methodsFor!

tag	^'span'! !
!ILSpanElement categoriesFor: #tag!accessing!public! !

