"Filed out from Dolphin Smalltalk 7"!

ILTableCellElement subclass: #ILTableHeaderElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableHeaderElement guid: (GUID fromString: '{3874d3fd-4d96-4916-8d7e-31f081a0a32a}')!
ILTableHeaderElement comment: ''!
!ILTableHeaderElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILTableHeaderElement methodsFor!

tag	^'th'! !
!ILTableHeaderElement categoriesFor: #tag!accessing!public! !

