"Filed out from Dolphin Smalltalk 7"!

ILWidget subclass: #ILWidgetMock2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILWidgetMock2 guid: (GUID fromString: '{00dd8027-a60b-42c0-9715-34627bc68d74}')!
ILWidgetMock2 comment: ''!
!ILWidgetMock2 categoriesForClass!Iliad-Tests-Buildables! !
!ILWidgetMock2 methodsFor!

contents	^[:e | e text: 'test widget 2']! !
!ILWidgetMock2 categoriesFor: #contents!building!public! !

