"Filed out from Dolphin Smalltalk 7"!

ILApplication subclass: #ILApplicationMock2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: 'path'!
ILApplicationMock2 guid: (GUID fromString: '{47f7252d-16e1-4965-93a7-f7198d9d2692}')!
ILApplicationMock2 comment: ''!
!ILApplicationMock2 categoriesForClass!Iliad-Tests-Buildables! !
!ILApplicationMock2 class methodsFor!

path	^path!

path: aString	path := aString! !
!ILApplicationMock2 class categoriesFor: #path!private! !
!ILApplicationMock2 class categoriesFor: #path:!private! !

