"Filed out from Dolphin Smalltalk 7"!

ILApplication subclass: #ILApplicationMock1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: 'path'!
ILApplicationMock1 guid: (GUID fromString: '{a586e05b-37f0-476e-bd6c-a8658bde51ac}')!
ILApplicationMock1 comment: ''!
!ILApplicationMock1 categoriesForClass!Iliad-Tests-Buildables! !
!ILApplicationMock1 class methodsFor!

path	^path!

path: aString	path := aString! !
!ILApplicationMock1 class categoriesFor: #path!private! !
!ILApplicationMock1 class categoriesFor: #path:!private! !

