"Filed out from Dolphin Smalltalk 7"!

GRError subclass: #ILAttributeError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILAttributeError guid: (GUID fromString: '{c6ea0f64-5a95-4935-9ce9-5a3f53e41444}')!
ILAttributeError comment: 'This exception is raised when a HTML element such as image, or table, misses a needed attribute.'!
!ILAttributeError categoriesForClass!Iliad-Core-Elements! !
