"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILCaptionElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILCaptionElement guid: (GUID fromString: '{4467a5e0-950f-4fbe-bf1e-9945f65e58d4}')!
ILCaptionElement comment: ''!
!ILCaptionElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILCaptionElement methodsFor!

tag	^'caption'! !
!ILCaptionElement categoriesFor: #tag!accessing!public! !

