"Filed out from Dolphin Smalltalk 7"!

ILAbstractSelectorApplication subclass: #ILClassSearchApplication
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILClassSearchApplication guid: (GUID fromString: '{0c613a75-39f4-4f88-81b7-d6d059500046}')!
ILClassSearchApplication comment: ''!
!ILClassSearchApplication categoriesForClass!Iliad-More-Examples! !
!ILClassSearchApplication methodsFor!

defaultWidget	^ ILClassSearchWidget new! !
!ILClassSearchApplication categoriesFor: #defaultWidget!defaults!public! !

!ILClassSearchApplication class methodsFor!

path	" Private - See superimplementor's comment "	^'examples/search'! !
!ILClassSearchApplication class categoriesFor: #path!accessing!public! !

