"Filed out from Dolphin Smalltalk 7"!

ILCometEvent subclass: #ILCometCounterChangedEvent
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILCometCounterChangedEvent guid: (GUID fromString: '{9cd3ae05-0c8c-446d-adf4-60f212312f41}')!
ILCometCounterChangedEvent comment: ''!
!ILCometCounterChangedEvent categoriesForClass!Iliad-More-CometExample! !
