"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILDatalistElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILDatalistElement guid: (GUID fromString: '{8f877b91-5938-409e-9a62-f457160b9934}')!
ILDatalistElement comment: 'An ILDatalistElement specifies a list of pre-defined options for an <input> element.The <datalist> tag is used to provide an "autocomplete" feature on <input> elements. Users will see a drop-down list of pre-defined options as they input data.Use the <input> element''s list attribute to bind it together with a <datalist> element.'!
!ILDatalistElement categoriesForClass!Iliad-More-HTML5Elements! !
!ILDatalistElement methodsFor!

tag	^'datalist'! !
!ILDatalistElement categoriesFor: #tag!accessing!public! !

