"Filed out from Dolphin Smalltalk 7"!

ILUIWidget subclass: #ILDataGridFooter
	instanceVariableNames: 'grid'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILDataGridFooter guid: (GUID fromString: '{5a600f94-8a43-48a1-a7c5-efe13eb8511f}')!
ILDataGridFooter comment: ''!
!ILDataGridFooter categoriesForClass!Iliad-More-UI! !
!ILDataGridFooter methodsFor!

contents	^[:e |		"nothing here"]!

grid	^grid!

grid: anObject	grid := anObject!

rootElementClass	^ILTableRowElement! !
!ILDataGridFooter categoriesFor: #contents!building!public! !
!ILDataGridFooter categoriesFor: #grid!accessing!public! !
!ILDataGridFooter categoriesFor: #grid:!accessing!public! !
!ILDataGridFooter categoriesFor: #rootElementClass!accessing!public! !

