"Filed out from Dolphin Smalltalk 7"!

ILObject subclass: #ILDirectory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILDirectory guid: (GUID fromString: '{a1ab7ab8-48c5-4c5a-90f3-7f82eab2ab4f}')!
ILDirectory comment: ''!
!ILDirectory categoriesForClass!Iliad-Core-RequestHandlers! !
!ILDirectory methodsFor!

fileContentsFor: aFilename	self subclassResponsibility! !
!ILDirectory categoriesFor: #fileContentsFor:!accessing!public! !

