"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILDivElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILDivElement guid: (GUID fromString: '{192964c8-428d-4ea9-add3-9a40e5919c86}')!
ILDivElement comment: ''!
!ILDivElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILDivElement methodsFor!

tag	^'div'! !
!ILDivElement categoriesFor: #tag!accessing!public! !

