"Filed out from Dolphin Smalltalk 7"!

ILClosingElement subclass: #ILHorizontalRuleElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILHorizontalRuleElement guid: (GUID fromString: '{c2e54d14-c883-470a-a9cd-2ae692e1b918}')!
ILHorizontalRuleElement comment: ''!
!ILHorizontalRuleElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILHorizontalRuleElement methodsFor!

onEvent: event add: aString 	self doesNotUnderstandAttribute: 'on', aString!

tag	^'hr'! !
!ILHorizontalRuleElement categoriesFor: #onEvent:add:!accessing attributes/events!public! !
!ILHorizontalRuleElement categoriesFor: #tag!accessing!public! !

