"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILLegendElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILLegendElement guid: (GUID fromString: '{b36e69f5-eeb2-40c6-9349-0ceaa2761ba0}')!
ILLegendElement comment: ''!
!ILLegendElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILLegendElement methodsFor!

accesskey: aCharacter 	self attributeAt: 'accesskey' put: aCharacter greaseString!

tag	^ 'legend'! !
!ILLegendElement categoriesFor: #accesskey:!accessing attributes!public! !
!ILLegendElement categoriesFor: #tag!accessing!public! !

