"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILListItemElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILListItemElement guid: (GUID fromString: '{685adfb8-51e0-4079-86b5-749a63027c84}')!
ILListItemElement comment: ''!
!ILListItemElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILListItemElement methodsFor!

tag	^'li'! !
!ILListItemElement categoriesFor: #tag!accessing!public! !

