"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILMapElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILMapElement guid: (GUID fromString: '{8410efb6-0f56-460b-9b78-5799a7a0f428}')!
ILMapElement comment: ''!
!ILMapElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILMapElement methodsFor!

classes: aCollection	ILAttributeError signal: 'map tag can have one class only'!

tag	^ 'map'! !
!ILMapElement categoriesFor: #classes:!accessing attributes!public! !
!ILMapElement categoriesFor: #tag!accessing!public! !

