"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILParagraphElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILParagraphElement guid: (GUID fromString: '{01e46cba-1da2-418b-b9c2-a888eb569dc2}')!
ILParagraphElement comment: ''!
!ILParagraphElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILParagraphElement methodsFor!

tag	^'p'! !
!ILParagraphElement categoriesFor: #tag!accessing!public! !

