"Filed out from Dolphin Smalltalk 7"!

Notification subclass: #ILResponseNotification
	instanceVariableNames: 'response'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILResponseNotification guid: (GUID fromString: '{8296c3f5-f17d-4312-8109-16ecab3065c9}')!
ILResponseNotification comment: ''!
!ILResponseNotification categoriesForClass!Iliad-Core-RequestHandlers! !
!ILResponseNotification methodsFor!

response	^response!

response: aResponse	response := aResponse! !
!ILResponseNotification categoriesFor: #response!accessing!public! !
!ILResponseNotification categoriesFor: #response:!accessing!public! !

