"Filed out from Dolphin Smalltalk 7"!

ILRSSElement subclass: #ILRSSCommentsElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILRSSCommentsElement guid: (GUID fromString: '{72a33141-47ff-4945-8f23-172efa9bdb8a}')!
ILRSSCommentsElement comment: ''!
!ILRSSCommentsElement categoriesForClass!Iliad-More-RSS! !
!ILRSSCommentsElement methodsFor!

tag	^'comments'! !
!ILRSSCommentsElement categoriesFor: #tag!accessing!public! !

