"Filed out from Dolphin Smalltalk 7"!

ILHTMLBuilderElement subclass: #ILRubyTextElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILRubyTextElement guid: (GUID fromString: '{dc09ba5a-0e76-45de-81b8-f5bf9092eb72}')!
ILRubyTextElement comment: ''!
!ILRubyTextElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILRubyTextElement methodsFor!

rbspan: anInteger 	self attributeAt: 'rbspan' put: anInteger greaseString!

tag	^ 'rt'! !
!ILRubyTextElement categoriesFor: #rbspan:!accessing attributes!public! !
!ILRubyTextElement categoriesFor: #tag!accessing!public! !

