"Filed out from Dolphin Smalltalk 7"!

ILTableElementElement subclass: #ILTableFootElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableFootElement guid: (GUID fromString: '{d45d7ed5-c1f9-42bb-bfe3-34856fd70bc2}')!
ILTableFootElement comment: ''!
!ILTableFootElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILTableFootElement methodsFor!

tag	^'tfoot'! !
!ILTableFootElement categoriesFor: #tag!accessing!public! !

