"Filed out from Dolphin Smalltalk 7"!

ILElementTest subclass: #ILTableHeaderElementTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableHeaderElementTest guid: (GUID fromString: '{6c6667e5-e263-4c4a-9c90-5d0f639f04e4}')!
ILTableHeaderElementTest comment: ''!
!ILTableHeaderElementTest categoriesForClass!Iliad-Tests-Elements! !
!ILTableHeaderElementTest methodsFor!

setUp	e := ILTableHeaderElement new!

testTag	self assert: e tag equals: 'th'! !
!ILTableHeaderElementTest categoriesFor: #setUp!public!running! !
!ILTableHeaderElementTest categoriesFor: #testTag!public!testing! !

