"Filed out from Dolphin Smalltalk 7"!

ILElementTest subclass: #ILTableFootElementTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableFootElementTest guid: (GUID fromString: '{bcee88a1-01ed-42ee-8de4-05d3fdbe8b7e}')!
ILTableFootElementTest comment: ''!
!ILTableFootElementTest categoriesForClass!Iliad-Tests-Elements! !
!ILTableFootElementTest methodsFor!

setUp	e := ILTableFootElement new!

testTag	self assert: e tag equals: 'tfoot'! !
!ILTableFootElementTest categoriesFor: #setUp!public!running! !
!ILTableFootElementTest categoriesFor: #testTag!public!testing! !

