"Filed out from Dolphin Smalltalk 7"!

ILTableElementElement subclass: #ILTableBodyElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableBodyElement guid: (GUID fromString: '{3b5316ab-fcb5-473f-987f-fa86f8549871}')!
ILTableBodyElement comment: ''!
!ILTableBodyElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILTableBodyElement methodsFor!

tag	^'tbody'! !
!ILTableBodyElement categoriesFor: #tag!accessing!public! !

