"Filed out from Dolphin Smalltalk 7"!

ILTableElementElement subclass: #ILTableHeadElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableHeadElement guid: (GUID fromString: '{b41209d8-df94-46b6-81ce-b68fd88736f2}')!
ILTableHeadElement comment: ''!
!ILTableHeadElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILTableHeadElement methodsFor!

tag	^'thead'! !
!ILTableHeadElement categoriesFor: #tag!accessing!public! !

