"Filed out from Dolphin Smalltalk 7"!

ILTableCellElement subclass: #ILTableRowElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableRowElement guid: (GUID fromString: '{7cf6f244-4e63-4230-94a2-ee40e241f5fd}')!
ILTableRowElement comment: ''!
!ILTableRowElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILTableRowElement methodsFor!

tag	^'tr'! !
!ILTableRowElement categoriesFor: #tag!accessing!public! !

