"Filed out from Dolphin Smalltalk 7"!

ILTableCellElement subclass: #ILTableDataElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILTableDataElement guid: (GUID fromString: '{8e99dd92-a252-41a5-bd10-6642d83cc324}')!
ILTableDataElement comment: ''!
!ILTableDataElement categoriesForClass!Iliad-Core-HTMLElements! !
!ILTableDataElement methodsFor!

tag	^'td'! !
!ILTableDataElement categoriesFor: #tag!accessing!public! !

