"Filed out from Dolphin Smalltalk 7"!

ILWidget subclass: #ILUIWidget
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILUIWidget guid: (GUID fromString: '{6bbfac35-1b33-458d-b1ac-65cfcc768655}')!
ILUIWidget comment: ''!
!ILUIWidget categoriesForClass!Iliad-More-UI! !
!ILUIWidget methodsFor!

cssClass	^'_ui'! !
!ILUIWidget categoriesFor: #cssClass!accessing!public! !

