"Filed out from Dolphin Smalltalk 7"!

ILWidget subclass: #ILWidgetMock3
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILWidgetMock3 guid: (GUID fromString: '{6c1a6833-12c5-464d-b62f-2c2f94514342}')!
ILWidgetMock3 comment: ''!
!ILWidgetMock3 categoriesForClass!Iliad-Tests-Buildables! !
!ILWidgetMock3 methodsFor!

contents	^[:e | e text: 'test widget 3']! !
!ILWidgetMock3 categoriesFor: #contents!building!public! !

