"Filed out from Dolphin Smalltalk 7"!

ILWidget subclass: #ILWidgetMock1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ILWidgetMock1 guid: (GUID fromString: '{25bb6a06-c057-47ce-b7f7-28d060ace2d7}')!
ILWidgetMock1 comment: ''!
!ILWidgetMock1 categoriesForClass!Iliad-Tests-Buildables! !
!ILWidgetMock1 methodsFor!

contents	^[:e | e text: 'test widget 1']! !
!ILWidgetMock1 categoriesFor: #contents!building!public! !

