"Filed out from Dolphin Smalltalk 7"!

PackageManifest subclass: #ManifestIliadTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ManifestIliadTests guid: (GUID fromString: '{93118759-32c5-400e-b0b6-56cabb9ee5d0}')!
ManifestIliadTests comment: 'I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser'!
!ManifestIliadTests categoriesForClass!Iliad-Tests! !
!ManifestIliadTests class methodsFor!

ruleRBBadMessageRuleV1FalsePositive	^ #(#(#(#RGClassDefinition #(#ILHTMLBuilderElementTest)) #'2017-10-01T21:31:21.202342+02:00') )! !
!ManifestIliadTests class categoriesFor: #ruleRBBadMessageRuleV1FalsePositive!code/critics!public! !

