"Filed out from Dolphin Smalltalk 7"!

FileStream subclass: #StandardFileStream
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
StandardFileStream guid: (GUID fromString: '{f260754a-6deb-4d52-84aa-588d719e2c6b}')!
StandardFileStream comment: ''!
!StandardFileStream categoriesForClass!Collections-Streams! !
!StandardFileStream class methodsFor!

forceNewFileNamed: aString

	^self write: aString! !
!StandardFileStream class categoriesFor: #forceNewFileNamed:!public! !

